# Generated by Django 3.0.8 on 2020-10-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_user',
        ),
    ]
