# Generated by Django 3.1.3 on 2020-11-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20201001_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='rooms.room'),
        ),
    ]
