# Generated by Django 3.0.8 on 2020-07-19 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Иван', max_length=30)),
                ('last_name', models.CharField(default='Иванович', max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='Не указан', max_length=100)),
                ('cover', models.ImageField(blank=True, default='images/covers/default.png', upload_to='images/covers/')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default='Статус пуст', max_length=200)),
                ('reputation', models.IntegerField(default=0)),
                ('best_answers', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('incoming_friend_requests', models.ManyToManyField(related_name='outgoing_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
